name: libresprite
version: '1.17-git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Animated sprite editor & pixel art tool
description: |
  LibreSprite is a free and open source program to create animated sprites.
  It is a fork of the last GPLv2 commit of Aseprite.

grade: stable
confinement: strict

apps:
  libresprite:
    command: bin/aseprite
    plugs:
      - home
      - unity7
      - x11

parts:
  libresprite:
    source: https://github.com/LibreSprite/LibreSprite.git
    plugin: cmake
    build-packages:
      - build-essential
      - libx11-dev
      - libxcursor-dev
      - ninja-build
    stage-packages:
      - libx11-6
      - libxrender1
      - libxfixes3
      - libxcursor1
